@URL = {{$dotenv VITE_SUPABASE_URL}}
@ANON_KEY = {{$dotenv VITE_SUPABASE_ANON_KEY}}

###
# @name ping
POST {{URL}}/functions/v1/ping
Authorization: Bearer {{ANON_KEY}}
Content-Type: application/json

{ "name": "ping" }
